server:
  port: 8090

spring:
  application:
    name: gateway

eureka:
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: productservice
        uri: lb://product-service
        predicates:
        - Path=/productservice/**
        filters:
        - RewritePath=/productservice/(?<path>.*), /$\{path}
      - id: shoppingcartservice
        uri: lb://shopping-cart-service
        predicates:
        - Path=/shoppingcartservice/**
        filters:
        - RewritePath=/shoppingcartservice/(?<path>.*), /$\{path}
      - id: deliveryservice
        uri: lb://delivery-service
        predicates:
        - Path=/deliveryservice/**
        filters:
        - RewritePath=/deliveryservice/(?<path>.*), /$\{path}
      - id: service2
        uri: lb://service-2
        predicates:
        - Path=/service2/**
        filters:
        - RewritePath=/service2/(?<path>.*), /$\{path}
      - id: service1
        uri: lb://service-1
        predicates:
        - Path=/service1/**
        filters:
        - RewritePath=/service1/(?<path>.*), /$\{path}